package scheme

import "database/sql"

type PkwTecdocArticleSrc struct {
	ArticleId                int            `db:"articleId"`
	OldTecdocId              int            `db:"oldTecdocId"`
	TecdocId                 int            `db:"tecdocId"`
	UserId                   int            `db:"userId"`
	GenericArticleId         int            `db:"genericArticleId"`
	Name                     string         `db:"Name"`
	AdditionalName           sql.NullString `db:"additionalName"`
	BrandNo                  int            `db:"brandNo"`
	UVP                      float32        `db:"UVP"`
	EAN                      string         `db:"EAN"`
	ArticleNo                string         `db:"articleNo"`
	Image                    string         `db:"Image"`
	Price                    float32        `db:"Price"`
	PriceNetto               float32        `db:"PriceNetto"`
	Weight                   float32        `db:"weight"`
	Width                    uint           `db:"width"`
	Length                   uint           `db:"length"`
	Height                   uint           `db:"height"`
	MeasurementsChecked      uint8          `db:"measurementsChecked"`
	CustomsCode              string         `db:"customsCode"`
	Date                     []uint8        `db:"Date"`
	IsDisabled               string         `db:"isDisabled"`
	IsNotAvailable           string         `db:"isNotAvailable"`
	Ammount                  int            `db:"Ammount"`
	DataSourceID             int            `db:"DataSourceID"`
	MoneyBack                float32        `db:"MoneyBack"`
	DeliveryCost             float32        `db:"DeliveryCost"`
	SurchargeEnabled         int8           `db:"surchargeEnabled"`
	Surcharge                float32        `db:"surcharge"`
	SurchargeChecked         int8           `db:"surchargeChecked"`
	SurchargeEnabledLkw      int8           `db:"surchargeEnabledLkw"`
	SurchargeLkw             float32        `db:"surchargeLkw"`
	HazardEnabled            int8           `db:"hazardEnabled"`
	HazardSum                float32        `db:"hazardSum"`
	PricePolicy              string         `db:"pricePolicy"`
	ArticleSet               int8           `db:"articleSet"`
	MirrorArticleId          sql.NullInt32  `db:"mirrorArticleId"`
	RandomSale               int8           `db:"randomSale"`
	Rock                     sql.NullInt32  `db:"rock"`
	LabelLkw                 int8           `db:"labelLkw"`
	MarketingRating          uint           `db:"marketingRating"`
	MarketingSales           uint           `db:"marketingSales"`
	MarketingSalesReplace    uint           `db:"marketingSalesReplace"`
	Label                    string         `db:"label"`
	LagerLabel               int8           `db:"lagerLabel"`
	LabelDate                []uint8        `db:"labelDate"`
	LogisticLabel            string         `db:"logisticLabel"`
	IsLabelImporting         int8           `db:"isLabelImporting"`
	FullApl                  int8           `db:"fullApl"`
	DifficultApplicability   bool           `db:"difficultApplicability"`
	IsNotProduction          sql.NullBool   `db:"isNotProduction"`
	ExistInTecdoc            bool           `db:"existInTecdoc"`
	Synthetic                int8           `db:"synthetic"`
	IsThirdPartyPlatformSale uint8          `db:"isThirdPartyPlatformSale"`
	Created                  []uint8        `db:"created"`
	Updated                  []uint8        `db:"updated"`
	Patent                   uint8          `db:"patent"`
	Stock                    int16          `db:"stock"`
	Transfer                 int16          `db:"transfer"`
	IsPreRequest             int8           `db:"isPreRequest"`
	State                    uint8          `db:"state"`
	IsEurope                 bool           `db:"isEurope"`
	WeightBrutto             float32        `db:"weightBrutto"`
	WeightDataSource         int            `db:"weightDataSource"`
	IsCustomKit              int            `db:"isCustomKit"`
	Seasonal                 bool           `db:"seasonal"`
	IsUnit                   sql.NullBool   `db:"isUnit"`
}
